print("1. Tarapacá")
print("2. Antofagasta")
print("3. Atacama")
print("4. Coquimbo")
print("5. Valparaiso")
print("6. O'Higgins")
print("7. Maule")
print("8. Biobío")
print("9. Araucanía")
print("10. Los Lagos")
print("11. Aysén")
print("12. Magallanes")
print("13. Metropolitana")
print("14. Los Ríos")
print("15. Arica y Parinacota")
 
regiones = input("Ingrese el numero de la Region que desea: ")
while regiones.isnumeric()!= True :
    print("Ese no es un numero de region")
    regiones = input("Ingrese el numero de la Region que desea:")